### ISSUE TITLE
Benutzerkonto - Logout vll. als Outline Button auf Desktop?

### ISSUE THREAD

**Issue by andreasellw** [tech4germany/zoll-auktion.de#53]

**Comment by ahmadmu** [comment]
ok ausgeblendet, müssen die anderen dann nach Meinung fragen

**Comment by andreasellw** [comment]
bzgl. oben dem button "Mein Konto" würde ich evtl sogar das Icon von Mobil stattdessen verwenden und daneben mit Text Mein Konto schreiben
