### ISSUE TITLE
Produktansicht - Farben und Anordnung von "Merken" überarbeiten

### ISSUE THREAD

**Issue by andreasellw** [tech4germany/zoll-auktion.de#75]

**Comment by ahmadmu** [comment]
Brauche Meinungen zu der Layout vom Merken auf Handy und Desktop

**Comment by andreasellw** [comment]
Jo hab es mir angeschaut, ich persönlich find, es passt jetzt erst mal so! :)
Aber können ja am Montag, wenn wir die Illustrationen dann auch noch eingefügt haben mit dem ganzen Team nochmal die Website im Detail durchgehen.
