### ISSUE TITLE
Landingpage - Top Auktion clearfix funktioniert nicht, Bilder sollten weiter nach unten rutschen

### ISSUE THREAD

**Issue by andreasellw** [tech4germany/zoll-auktion.de#90]

**Comment by andreasellw** [comment]
Aktuell nicht möglich, muss evtl. nocheinmal gerefactored werden damit es via flex funktioniert.

**Comment by ahmadmu** [comment]
oder die höhe ändern? siehe meine aktuelle Lösung. Das hat nichts mit clearfix zu tun übrigens, clearfix dient einfach dazu, die floats zurückzusetzen damit hier der Preis im Parent-div liegen bleibt.

**Comment by andreasellw** [comment]
ja hatte damals ausversehen clearfix in den titel reingeschrieben. du hast seit gestern nicht mehr gepusht.
